### ISSUE TITLE
Curation contract return details

### ISSUE THREAD

**Issue by dblodorn** [public-assembly/neosound#28]
- [x] public-assembly/neosound#29
- [x] public-assembly/neosound#30
- [x] public-assembly/zora-drops-utils#59
